merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', views.band_list, name='band-list'),
	path('bands/<int:id>/', views.band_detail, name='band-detail'),
	path('band_add/', views.band_add, name='band-add'),
	path('band_update/<int:id>/', views.band_update, name='band-update'),
	path('band_delete/<int:id>/', views.band_delete, name='band-delete'),
	path('about_us/', views.about_us, name='about-us'),
	path('listing/', views.listing, name='listing'),
	path('listing/<int:id>', views.listing_detail, name='listing-detail'),
	path('listing_add/', views.listing_add, name='listing-add'),
	path('listing_update/<int:id>/', views.listing_update, name='listing-update'),
	path('listing_delete/<int:id>/', views.listing_delete, name='listing-delete'),
	path('contact/', views.contactUs, name='contact-us'),
	path('email-sent/', views.email_sent, name='email-sent'),
]

merchex/listings/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.
class Band(models.Model):

	class Genre(models.TextChoices):
		HIP_HOP = 'HH'
		SYNTH_POP = 'SP'
		ALTERNATIVE_ROCK = 'AR'
		JAZZ = 'JA'
		VARIETE_FR = 'VF'

	name = models.fields.CharField(max_length=100)
	slug = models.SlugField(max_length=100)
	genre = models.fields.CharField(choices=Genre.choices, max_length=5)
	biography = models.fields.CharField(max_length=1000)
	year_formed = models.fields.IntegerField(
		validators=[MinValueValidator(1900), MaxValueValidator(2024)]
	)
	active = models.fields.BooleanField(default=True)
	official_homepage = models.fields.URLField(null=True, blank=True)

#def ecriture du nom ds la bd
	def __str__(self):
		return f"{self.name}"

##btn pr voir sur le site ds la bd
	def get_absolute_url(self):
		return reverse("band", kwargs={"slug": self.slug})

class Listing(models.Model):
	class ListingType(models.TextChoices):
		RECORDS = 'R'
		CLOTHING = 'C'
		POSTERS = 'P'
		MISC = 'M'

	title = models.fields.CharField(max_length=100)
	slug = models.SlugField(max_length=100)
	description = models.fields.CharField(max_length=1000)
	sold = models.fields.BooleanField(default=False)
	year_formed = models.fields.IntegerField(
		null=True,
		validators=[MinValueValidator(1900), MaxValueValidator(2024)]
	)
	type = models.fields.CharField(choices=ListingType.choices, max_length=5)
	band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL) #ajout cle etrangere ds model Listings(issut de la class band)

	#définir le champ band comme nul en utilisant models.SET_NULL,

	#définir le champ band à sa valeur par défaut en utilisant models.SET_DEFAULT,

	#supprimer l'objet Listing en utilisant models.CASCADE,

	#et d'autres paramètres plus complexes que vous pouvez trouver décrits dans la documentation de Django.

	#Nous ne voulons pas supprimer l'objet Listing si un Band est supprimé, nous utiliserons donc SET_NULL.
	
	#def ecriture du nom ds la bd
	def __str__(self):
		return f"{self.title}"

merchex/listings/forms.py
from django import forms
from listings.models import Band, Listing

class ContactUsForm(forms.Form):
	name = forms.CharField(required=False)
	email = forms.EmailField(required=False)
	message = forms.CharField(max_length=1000)

class AddBandForm(forms.ModelForm):
	class Meta: #cpy class Band
		model = Band #name of cpy
		#fields = '__all__' #cpy all
		exclude = ('slug', 'active', 'official_homepage')

class AddListingForm(forms.ModelForm):
	class Meta:
		model = Listing
		exclude = ('slug', 'sold')

merchex/listings/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from listings.models import Band, Listing
from listings.forms import ContactUsForm, AddBandForm, AddListingForm
from django.core.mail import send_mail

def band_list(request):
	bands = Band.objects.all()
	return render(request, 'listings/band_list.html', {'bands': bands})

def band_detail(request, id):
	#return render(request, 'listings/band_detail.html',	{'id': id})
	band = Band.objects.get(id=id)
	return render(request, 'listings/band_detail.html',	{'band': band})

def about_us(request):
	#return HttpResponse('<h1>A propos</h1> <p>Nous adorons march!</p>')
	return render(request, 'listings/about_us.html')

def listing(request):
	listings = Listing.objects.all()
	return render(request, 'listings/listing.html', {'listings': listings})

def listing_detail(request, id):
	listing = Listing.objects.get(id=id)
	return render(request, 'listings/listing_detail.html',	{'listing': listing})

def contactUs(request):
	#print('La methode requete est : ', request.method)
	#print('Les donnes POST sont : ', request.POST)
	if request.method == 'POST': #fill form
		form = ContactUsForm(request.POST)
		if form.is_valid():
			send_mail(
				subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
				message=form.cleaned_data['message'],
				from_email=form.cleaned_data['email'],
				recipient_list=['admin@merchex.xyz'],
			)
		return redirect('email-sent')
	else: #request GET -> empty form
		form = ContactUsForm()
	return render(request, 'listings/contact_us.html', {'form': form}) #pass this form at gabarit

def email_sent(request):
	return render(request, 'listings/email_sent.html')

def band_add(request):
	if request.method == 'POST':
		form = AddBandForm(request.POST)
		if form.is_valid():
			band = form.save()
			return redirect('band-detail', band.id)
	else:
		form = AddBandForm()
	return render(request, 'listings/band_add.html', {'form': form})

def listing_add(request):
	if (request.method == 'POST'):
		form = AddListingForm(request.POST)
		if form.is_valid():
			listing = form.save()
			return redirect('listing')
	else:
		form = AddListingForm()
	return render(request, 'listings/listing_add.html', {'form': form})

def band_update(request, id):
	band = Band.objects.get(id=id)
	if request.method == 'POST':
		form = AddBandForm(request.POST, instance=band)
		if form.is_valid():
			form.save()
			return redirect('band-detail', band.id)
	else:
		form = AddBandForm(instance=band)
	return render(request, 'listings/band_update.html', {'form': form})

def listing_update(request, id):
	listing = Listing.objects.get(id=id)
	if request.method == 'POST':
		form = AddListingForm(request.POST, instance=listing)
		if form.is_valid():
			form.save()
			return redirect('listing-detail', listing.id)
	else:
		form = AddListingForm(instance=listing)
	return render(request, 'listings/listing_update.html', {'form': form})

def band_delete(request, id):
	band = Band.objects.get(id=id)
	if request.method == 'POST':
		band.delete()
		return redirect('band-list')
	return render(request, 'listings/band_delete.html', {'band': band})

def listing_delete(request, id):
	listing = Listing.objects.get(id=id)
	if request.method == 'POST':
		listing.delete()
		return redirect('listing')
	return render(request, 'listings/listing_delete.html',	{'listing': listing})

merchex/listings/templates/listings/about_us.html
{% extends 'listings/base.html' %}
{% block content %}
<a href="{% url 'band-list' %}">Groupes - </a>
<a href="{% url 'listing' %}">Liste - </a>
<a href="{% url 'contact-us' %}">Conactez-nous</a>
<h1>About Us</h1>
<p>Hello I'm Blandine!</p>
<p>I'm dev, to serve you!</p>
<p>Please write me here</p>

{% endblock %}

merchex/listings/templates/listings/band_add.html
{% extends 'listings/base.html' %}

{% block content %}
<a href="{% url 'band-list' %}">Groupes - </a>
<a href="{% url 'listing' %}">Liste - </a>
<a href="{% url 'about-us' %}">A propos de nous - </a>
<a href="{% url 'contact-us' %}">Conactez-nous</a>

<h1>Creer nouveau groupe</h1>
<!--<form action="" method="post" novalidate>-->
<form action="" method="post" >
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}
<a href="{% url 'band-list' %}">Groupes - </a>
<a href="{% url 'listing' %}">Liste - </a>
<a href="{% url 'about-us' %}">A propos de nous - </a>
<a href="{% url 'contact-us' %}">Conactez-nous</a>

<h1>Supprimer le groupe</h1>
<!--<form action="" method="post" novalidate>-->
<p>Etes-vous sur de vouloir supprimer le groupe : {{ band.name }}?</p>
<form action="" method="post" >
	{% csrf_token %}
	<input type="submit" value="Supprimer">
</form>

{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}
<a href="{% url 'band-list' %}">Groupes - </a>
<a href="{% url 'listing' %}">Liste - </a>
<a href="{% url 'about-us' %}">A propos de nous - </a>
<a href="{% url 'contact-us' %}">Conactez-nous</a>
<h2>{{ band.name }}</h2>
<ul>
	<li>Genre: {{ band.get_genre_display }}</li>
	<li>Annee de formation: {{ band.year_formed }}</li>
	<li>Actif: {{ band.active|yesno }}</li>
	{% if band.official_homepage %}
		<li><a href="{{ band.officiql_homepage }}">{{ band.offocial_homepage }}</a></li>
	{% endif %}
	</ul>
<p>{{ band.biography }}</p>

<a href="{% url 'band-update' band.id %}">Editer ce groupe</a>

{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}
{% block content %}
<a href="{% url 'listing' %}">Liste - </a>
<a href="{% url 'about-us' %}">A propos de nous - </a>
<a href="{% url 'contact-us' %}">Conactez-nous</a>
<h1>Groupes</h1>

<!--<p>J'ai {{ bands|length }} groupes préférés</p>

<p>Mes groupes préférés sont :</p>-->
<p><a href="{% url 'band-add' %}">Creer un nouveau groupe</a></p>

<ul>

	{% for band in bands %}

	<li>
		<a href="{% url 'band-detail' band.id %}">{{ band.name|upper }}</a>
		- <a href="{% url 'band-update' band.id %}">[Modifier]</a>
		- <a href="{% url 'band-delete' band.id %}">[Supprimer]</a>
	</li>

	{% endfor %}

</ul>
<h3>Hey! Envie de nous dire quelque chose?</h3>
	<p>C'est juste <a href="{% url 'contact-us' %}">ici</a></p>
{% endblock %}

merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}
<a href="{% url 'band-list' %}">Groupes - </a>
<a href="{% url 'listing' %}">Liste - </a>
<a href="{% url 'about-us' %}">A propos de nous - </a>
<a href="{% url 'contact-us' %}">Conactez-nous</a>

<h1>Mise a jour du groupe</h1>
<!--<form action="" method="post" novalidate>-->
<form action="" method="post" >
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Merchex</title> 
	<link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
</head>
<body>
	
	{% block content %}
	{% endblock %}
</body>
</html>

merchex/listings/templates/listings/contact_us.html
{% extends 'listings/base.html' %}
{% block content %}
<a href="{% url 'band-list' %}">Groupes - </a>
<a href="{% url 'listing' %}">Liste - </a>
<a href="{% url 'about-us' %}">A propos de nous - </a>

<h1>Contact Us!</h1>
<p>Nous sommes la pour vous aider</p>
<!--<form action="" method="post" novalidate>-->
<form action="" method="post">
	<!-- csrf Cross Site Request Forgery -->
	{% csrf_token %}
	<!-- form.as_p pr mettre des espaces entre les lignes-->
	{{ form.as_p }}
	<input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}
{% block content %}

<h1>Message envoye!</h1>
<p>Merci nous reviendrons vers vous des que possible</p>
<a href="{% url 'band-list' %}">Retour a la liste</a>

{% endblock %}

merchex/listings/templates/listings/listing.html
{% extends 'listings/base.html' %}
{% block content %}
<a href="{% url 'band-list' %}">Groupes - </a>
<a href="{% url 'about-us' %}">A propos de nous - </a>
<a href="{% url 'contact-us' %}">Conactez-nous</a>
<h1>Listing</h1>
<a href="{% url 'listing-add' %}">Creer un nouveau listing</a>
<ul>

	{% for listing in listings %}
	<li>
		<a href="{% url 'listing-detail' listing.id %}">{{ listing.title|upper }}</a>
		- <a href="{% url 'listing-update' listing.id %}">[Modifier]</a>
		- <a href="{% url 'listing-delete' listing.id %}">[Supprimer]</a>
	</li>

	{% endfor %}

</ul>
{% endblock %}

merchex/listings/templates/listings/listing_add.html
{% extends 'listings/base.html' %}

{% block content %}
<a href="{% url 'band-list' %}">Groupes - </a>
<a href="{% url 'listing' %}">Liste - </a>
<a href="{% url 'about-us' %}">A propos de nous - </a>
<a href="{% url 'contact-us' %}">Conactez-nous</a>

<h1>Creer nouveau listing</h1>
<!--<form action="" method="post" novalidate>-->
<form action="" method="post" >
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/listing_delete.html
{% extends 'listings/base.html' %}

{% block content %}
<a href="{% url 'band-list' %}">Groupes - </a>
<a href="{% url 'listing' %}">Liste - </a>
<a href="{% url 'about-us' %}">A propos de nous - </a>
<a href="{% url 'contact-us' %}">Conactez-nous</a>

<h1>Supprimer ce listing</h1>
<!--<form action="" method="post" novalidate>-->
<p>Etes-vous sur de vouloir supprimer cette liste : {{ listing.title }}?</p>
<form action="" method="post" >
	{% csrf_token %}
	<input type="submit" value="Supprimer">
</form>

{% endblock %}

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}

{% block content %}
<a href="{% url 'band-list' %}">Groupes - </a>
<a href="{% url 'listing' %}">Liste - </a>
<a href="{% url 'about-us' %}">A propos de nous - </a>
<a href="{% url 'contact-us' %}">Conactez-nous</a>
<h2>{{ listing.title }}</h2>
<ul>
	<li>type: {{ listing.get_genre_display }}</li>
	<li>Annee: {{ listing.year_formed }}</li>
	<li>sold: {{ listing.sold|yesno }}</li>
	</ul>
<p>{{ listing.description }}</p>


{% endblock %}

merchex/listings/templates/listings/listing_update.html
{% extends 'listings/base.html' %}

{% block content %}
<a href="{% url 'band-list' %}">Groupes - </a>
<a href="{% url 'listing' %}">Liste - </a>
<a href="{% url 'about-us' %}">A propos de nous - </a>
<a href="{% url 'contact-us' %}">Conactez-nous</a>

<h1>Modifier ce listing</h1>
<!--<form action="" method="post" novalidate>-->
<form action="" method="post" >
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Envoyer">
</form>

{% endblock %}